import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

/**
 * The app layer: what can be checked without Xcode or Android Studio.
 *
 * The native projects, their icons and splash screens, the Capacitor config,
 * the iOS app-bound domain and the desktop shell are all generated or written
 * from this repo. These tests hold them to the shape the stores and the
 * platforms actually require — an opaque 1024 icon, the launcher densities,
 * the night colours everywhere — so a placeholder never ships by accident.
 *
 * Synced web assets are build artifacts (gitignored); those checks run only
 * when `npm run app:sync` has been run, which CI does before `npm test`.
 */
const root = fileURLToPath(new URL('..', import.meta.url));
const at = (p: string) => `${root}${p}`;
const png = (p: string) => {
  const b = readFileSync(at(p));
  assert.equal(b.subarray(1, 4).toString(), 'PNG', `${p} is a PNG`);
  return { width: b.readUInt32BE(16), height: b.readUInt32BE(20), colourType: b[25] };
};
const NIGHT = '#080D16';

describe('capacitor config', () => {
  it('names the app, points at public/, and carries the night look', async () => {
    const { default: config } = await import('../capacitor.config.ts');
    assert.equal(config.appId, 'org.commons.app');
    assert.equal(config.appName, 'Commons');
    assert.equal(config.webDir, 'public');
    assert.ok(config.server?.url, 'a server URL is set');
    assert.equal(config.server?.androidScheme, 'https');
    assert.equal(config.plugins?.SplashScreen?.backgroundColor, `${NIGHT}FF`);
    assert.equal(config.plugins?.StatusBar?.backgroundColor, NIGHT);
    assert.equal(config.plugins?.StatusBar?.style, 'DARK', 'light text on the night header');
    assert.equal(config.ios?.limitsNavigationsToAppBoundDomains, true, 'service workers in WKWebView need app-bound domains');
  });

  it('only allows cleartext for an http:// development address', async () => {
    const { default: config } = await import('../capacitor.config.ts');
    const url = config.server?.url ?? '';
    assert.equal(config.server?.cleartext, url.startsWith('http://'));
    if (!url.startsWith('http://')) assert.ok(url.startsWith('https://'), `server URL must be https, got ${url}`);
  });

  it('matches the manifest and the header colour', () => {
    const manifest = JSON.parse(readFileSync(at('public/manifest.webmanifest'), 'utf8')) as { theme_color: string };
    assert.equal(manifest.theme_color, NIGHT);
    const html = readFileSync(at('public/index.html'), 'utf8');
    assert.ok(html.includes(`<meta name="theme-color" content="${NIGHT}">`));
  });

  it('shares its app id with the desktop build', () => {
    const pkg = JSON.parse(readFileSync(at('package.json'), 'utf8')) as { build?: { appId?: string; productName?: string }; scripts: Record<string, string>; main?: string };
    assert.equal(pkg.build?.appId, 'org.commons.app');
    assert.equal(pkg.build?.productName, 'Commons');
    assert.equal(pkg.main, 'desktop/main.js');
    for (const s of ['app:sync', 'app:android', 'app:ios', 'desktop']) assert.ok(pkg.scripts[s], `npm run ${s} exists`);
  });
});

describe('native projects', () => {
  it('both exist, generated by Capacitor', () => {
    for (const p of [
      'android/app/src/main/AndroidManifest.xml', 'android/build.gradle', 'android/settings.gradle',
      'ios/App/App.xcodeproj/project.pbxproj', 'ios/App/App/Info.plist', 'ios/App/CapApp-SPM/Package.swift',
    ]) assert.ok(existsSync(at(p)), `${p} exists`);
  });

  it('are kept out of the Docker image', () => {
    const ignore = readFileSync(at('.dockerignore'), 'utf8').split('\n');
    for (const d of ['android', 'ios', 'desktop']) assert.ok(ignore.includes(d), `.dockerignore lists ${d}`);
  });
});

describe('native icons and splash screens', () => {
  it('Android launcher icons exist at every density, with round and adaptive variants', () => {
    for (const [d, size] of Object.entries({ mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 })) {
      for (const name of ['ic_launcher', 'ic_launcher_round']) {
        const s = png(`android/app/src/main/res/mipmap-${d}/${name}.png`);
        assert.deepEqual([s.width, s.height], [size, size], `${d}/${name}`);
      }
      const fg = png(`android/app/src/main/res/mipmap-${d}/ic_launcher_foreground.png`);
      assert.equal(fg.width, Math.round(size * 2.25), `${d} adaptive foreground is 108dp-based`);
      assert.equal(fg.colourType, 6, 'the foreground layer is transparent around the mark');
    }
    assert.ok(readFileSync(at('android/app/src/main/res/values/ic_launcher_background.xml'), 'utf8').includes(NIGHT));
    assert.ok(readFileSync(at('android/app/src/main/res/drawable/ic_launcher_background.xml'), 'utf8').includes(NIGHT));
    assert.ok(readFileSync(at('android/app/src/main/res/values/styles.xml'), 'utf8').includes(`windowSplashScreenBackground">${NIGHT}`));
  });

  it('Android splash screens exist in portrait and landscape at every density', () => {
    for (const d of ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']) {
      const port = png(`android/app/src/main/res/drawable-port-${d}/splash.png`);
      const land = png(`android/app/src/main/res/drawable-land-${d}/splash.png`);
      assert.ok(port.height > port.width, `${d} portrait is taller than wide`);
      assert.ok(land.width > land.height, `${d} landscape is wider than tall`);
    }
  });

  it('the iOS App Store icon is 1024×1024 with no alpha channel (ITMS-90717)', () => {
    const s = png('ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png');
    assert.deepEqual([s.width, s.height], [1024, 1024]);
    assert.equal(s.colourType, 2, 'RGB, no alpha channel at all');
  });

  it('the iOS splash is 2732×2732 in all three slots', () => {
    for (const name of ['splash-2732x2732.png', 'splash-2732x2732-1.png', 'splash-2732x2732-2.png']) {
      const s = png(`ios/App/App/Assets.xcassets/Splash.imageset/${name}`);
      assert.deepEqual([s.width, s.height], [2732, 2732], name);
    }
  });

  it('web icons and native icons are drawn from the same mark', () => {
    const mark = readFileSync(at('scripts/lib/mark.mjs'), 'utf8');
    for (const script of ['scripts/make-icons.mjs', 'scripts/app-assets.mjs']) {
      assert.ok(readFileSync(at(script), 'utf8').includes("from './lib/mark.mjs'"), `${script} imports the shared mark`);
    }
    assert.ok(mark.includes('0x08, 0x0d, 0x16'), 'the mark is drawn on the night (#080D16)');
  });
});

describe('after npm run app:sync (skipped until it has been run)', () => {
  const synced = existsSync(at('ios/App/App/capacitor.config.json')) && existsSync(at('android/app/src/main/assets/public/index.html'));

  it('both projects resolve to the same app and the same server', { skip: !synced }, () => {
    // Capacitor writes each platform its own view of the config, so the files
    // differ in platform keys; what must agree is who this is and where it loads.
    type Resolved = { appId: string; appName: string; webDir: string; server: { url: string; cleartext?: boolean } };
    const a = JSON.parse(readFileSync(at('android/app/src/main/assets/capacitor.config.json'), 'utf8')) as Resolved;
    const b = JSON.parse(readFileSync(at('ios/App/App/capacitor.config.json'), 'utf8')) as Resolved;
    for (const k of ['appId', 'appName', 'webDir'] as const) assert.equal(a[k], b[k], k);
    assert.deepEqual(a.server, b.server, 'the same server, the same cleartext rule');
    assert.ok(a.server.url.startsWith('https://') || a.server.url.startsWith('http://'));
  });

  it('the web assets inside both apps are exactly public/', { skip: !synced }, () => {
    for (const f of ['index.html', 'commons.js', 'commons.css', 'ambient.js', 'sw.js', 'manifest.webmanifest']) {
      const src = readFileSync(at(`public/${f}`));
      assert.ok(src.equals(readFileSync(at(`android/app/src/main/assets/public/${f}`))), `android ${f}`);
      assert.ok(src.equals(readFileSync(at(`ios/App/App/public/${f}`))), `ios ${f}`);
    }
  });

  it('the iOS app-bound domain is the server the app loads', { skip: !synced }, () => {
    const { server } = JSON.parse(readFileSync(at('ios/App/App/capacitor.config.json'), 'utf8')) as { server: { url: string } };
    const host = new URL(server.url).hostname;
    const plist = readFileSync(at('ios/App/App/Info.plist'), 'utf8');
    assert.ok(plist.includes('<key>WKAppBoundDomains</key>'), 'WKAppBoundDomains is set');
    assert.ok(plist.includes(`<string>${host}</string>`), `app-bound domain is ${host}`);
  });
});

describe('desktop shell', () => {
  it('its scripts parse, and the window opens onto a server rather than bundling one', () => {
    for (const f of ['desktop/main.js', 'desktop/setup-preload.js']) {
      const r = spawnSync(process.execPath, ['--check', at(f)], { encoding: 'utf8' });
      assert.equal(r.status, 0, `${f}: ${r.stderr}`);
    }
    const main = readFileSync(at('desktop/main.js'), 'utf8');
    assert.ok(main.includes('nodeIntegration: false') && main.includes('contextIsolation: true') && main.includes('sandbox: true'));
    assert.ok(main.includes('win.loadURL(origin)'), 'loads a remote Commons');
    assert.equal(main.includes("require('../src"), false, 'never runs the server inside the app');
  });
});
