import type Anthropic from '@anthropic-ai/sdk';
import { zodOutputFormat } from '@anthropic-ai/sdk/helpers/zod';
import { z } from 'zod';
import { RefusalError, withCategory } from '../refusal.ts';
import { BENCHMARKS } from './benchmarks.ts';
import { deriveSeries } from './metrics.ts';
import type { Business, Diagnosis } from './types.ts';

/** How many months of history the briefing call gets to see. */
const HISTORY_MONTHS = 6;

const BriefingSchema = z.object({
  headline: z
    .string()
    .describe(
      'One sentence naming the single most important thing about this business right now. Lead with the number that makes it true.',
    ),
  topMoves: z
    .array(
      z.object({
        title: z.string().describe('The move, as an instruction. Six to twelve words.'),
        why: z
          .string()
          .describe(
            'Why this one, citing the specific figure from the data that makes it urgent. No generic reasoning.',
          ),
        firstStep: z
          .string()
          .describe(
            'The first concrete action, small enough to start within a day and specific enough that its completion is unambiguous.',
          ),
        impact: z
          .enum(['high', 'medium', 'low'])
          .describe('Expected effect on the weakest pillar if this is done well.'),
        effortDays: z
          .number()
          .describe('Rough working days of effort. Be realistic, not optimistic.'),
      }),
    )
    .min(2)
    .max(4)
    .describe('Ordered: the first is what you would do if you could only do one thing.'),
  stopDoing: z
    .array(z.string())
    .max(3)
    .describe(
      'Things the figures suggest are consuming money or attention without returning either. Empty when the data does not support naming any.',
    ),
  biggestRisk: z.object({
    risk: z.string().describe('The thing most likely to seriously damage this business.'),
    earlyWarningSign: z
      .string()
      .describe('The observable signal that this is starting to happen, ideally a number they already track.'),
    mitigation: z.string().describe('What reduces it, in practical terms.'),
  }),
  questionToAnswer: z
    .string()
    .describe(
      'The one question whose answer would change what they do next. Something they can go and find out, not something to ponder.',
    ),
  dataGaps: z
    .array(z.string())
    .max(4)
    .describe(
      'Figures that are missing and would materially change this advice if known. Name the figure, not a vague area.',
    ),
});

export type Briefing = z.infer<typeof BriefingSchema>;

const SYSTEM_PROMPT = `You are an operator who has run and fixed businesses, writing a monthly briefing for one owner. You are given their real figures, the ratios computed from them, and a rules-based diagnosis that has already scored each area against benchmarks for their business model.

Your job is judgement, not arithmetic. The numbers and the scoring are already done and are shown to the owner alongside your briefing — do not restate them as advice. What you add is prioritisation, the causal reading that connects two symptoms into one cause, and the move a spreadsheet cannot name.

Rules:
- Cite the owner's actual figures. Every claim you make should be traceable to a number you were given.
- Never invent a figure. If something you need was not provided, put it in dataGaps and reason without it.
- Prefer the move that fixes a cause over the move that treats a symptom, and say which is which.
- Sequence matters: when cash is short, everything that spends cash waits, and you should say so plainly.
- Assume a small team with limited money and no spare hours. Advice that requires a department is worthless here.
- Be direct. If the business is in trouble, say it in the first sentence. Owners are not helped by encouragement that outruns the evidence.
- When the figures look healthy, do not manufacture alarm. The honest briefing for a good month is about what to compound and what would break it.`;

export interface BriefingInput {
  business: Business;
  diagnosis: Diagnosis;
}

/**
 * Ask Claude for the layer the rules engine cannot produce: what to do first,
 * and why these particular numbers point at that.
 *
 * The deterministic diagnosis goes into the prompt rather than being
 * regenerated by the model — the scores stay reproducible, and the model spends
 * its effort on prioritisation instead of re-deriving ratios it would get
 * slightly differently each time.
 */
export async function writeBriefing(
  client: Anthropic,
  { business, diagnosis }: BriefingInput,
): Promise<Briefing> {
  const history = deriveSeries(business.snapshots).slice(-HISTORY_MONTHS);

  const context = {
    business: {
      name: business.name,
      industry: business.industry,
      model: business.model,
      stage: business.stage,
      currency: business.currency,
      ownerGoals: business.goals,
    },
    benchmarksUsed: BENCHMARKS[business.model],
    monthlyHistory: history.map(round),
    diagnosis: {
      overallScore: diagnosis.overallScore,
      coverage: diagnosis.coverage,
      pillars: diagnosis.pillars.map((p) => ({
        pillar: p.pillar,
        score: p.score,
        missingInputs: p.missing,
      })),
      findings: diagnosis.priorities.map((f) => ({
        id: f.id,
        severity: f.severity,
        title: f.title,
        evidence: f.evidence,
      })),
    },
  };

  const response = await client.messages.parse({
    model: 'claude-opus-5',
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    // Prioritising across five interacting pillars is the reasoning-heavy part
    // of this product; low effort here produces bland, obvious advice.
    output_config: {
      effort: 'high',
      format: zodOutputFormat(BriefingSchema),
    },
    messages: [
      {
        role: 'user',
        content: `Write this month's briefing. All money figures are in minor units (cents) of ${business.currency}; ratios are fractions, not percentages.\n\n${JSON.stringify(context, null, 2)}`,
      },
    ],
  });

  if (response.stop_reason === 'refusal') {
    const category = response.stop_details?.category;
    throw new RefusalError(
      withCategory('Claude declined to write a briefing for this business', category) + '.',
      category,
    );
  }
  if (response.stop_reason === 'max_tokens') {
    throw new Error('The briefing was cut off before completing. Try again.');
  }

  const parsed = response.parsed_output;
  if (!parsed) throw new Error('Model returned no structured briefing.');
  return parsed;
}

/** Trim the long floats the ratio maths produces — they cost tokens and imply
 *  a precision the underlying figures do not have. */
function round(obj: object): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    out[key] = typeof value === 'number' ? Number(value.toFixed(4)) : value;
  }
  return out;
}
